(function(){
var ESPN='https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?dates=',rodando=false,ultima=0;
var alias={'brasil':'brazil','brazil':'brazil','czechia':'czech republic','czech rep':'czech republic','bosnia and herzegovina':'bosnia herzegovina','bosnia herzegovina':'bosnia herzegovina','ivory coast':'cote d ivoire','cote d ivoire':'cote d ivoire','usa':'united states','united states':'united states','south korea':'south korea','korea republic':'south korea','turkey':'turkiye','turkiye':'turkiye','netherlands':'netherlands','dr congo':'dr congo','congo dr':'dr congo','cape verde':'cape verde','saudi arabia':'saudi arabia','south africa':'south africa','new zealand':'new zealand'};
function limpar(x){return String(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9 ]+/g,' ').replace(/\s+/g,' ').trim().toLowerCase()}
function canon(x){var n=limpar(x);return alias[n]||n}
function chave(d,a,b){return d+'|'+canon(a)+'|'+canon(b)}
function dh(j){return new Date(j.date+'T'+j.time+':00-03:00')}
function estilo(){if(document.getElementById('placar-auto-brasil-css'))return;var s=document.createElement('style');s.id='placar-auto-brasil-css';s.textContent='.brasil-destaque{background:linear-gradient(90deg,rgba(34,197,94,.38),rgba(250,204,21,.22),rgba(34,197,94,.12))!important;border-color:rgba(250,204,21,.75)!important;box-shadow:0 0 22px rgba(34,197,94,.28),inset 5px 0 0 #22c55e!important}.match.brasil-destaque{border:2px solid rgba(250,204,21,.82)!important;position:relative}.match.brasil-destaque:before{content:"🇧🇷 JOGO DO BRASIL";display:inline-flex;margin-bottom:9px;padding:6px 10px;border-radius:999px;background:linear-gradient(135deg,rgba(34,197,94,.42),rgba(250,204,21,.28));border:1px solid rgba(250,204,21,.72);color:#fef9c3;font-size:12px;font-weight:900;letter-spacing:.06em}';document.head.appendChild(s)}
function marcarBrasil(){estilo();document.querySelectorAll('tr,.match').forEach(function(el){var t=(el.textContent||'').toLowerCase();if(t.indexOf('brasil')>=0||t.indexOf('brazil')>=0||el.querySelector('[alt="Brasil"],[alt="Brazil"]'))el.classList.add('brasil-destaque')})}
function datas(){try{if(typeof G==='undefined')return[];var ini=new Date(Date.now()-8*86400000),fim=new Date(Date.now()+3*3600000),set={},todos=[];if(Array.isArray(G))todos=todos.concat(G);if(typeof KO!=='undefined'&&Array.isArray(KO))todos=todos.concat(KO);todos.forEach(function(j){if(!j||!j.date||!j.time)return;var d=dh(j);if(d>=ini&&d<=fim)set[String(j.date).replace(/-/g,'')]=true});return Object.keys(set).sort()}catch(e){return[]}}
async function buscar(forcar){var agora=Date.now();if(rodando)return;if(!forcar&&agora-ultima<20000)return;if(typeof S==='undefined'||typeof render!=='function')return;rodando=true;ultima=agora;var mudou=false;try{await Promise.all(datas().map(async function(dia){try{var r=await fetch(ESPN+dia+'&_='+Date.now(),{cache:'no-store',mode:'cors',credentials:'omit'});if(!r.ok)return;var js=await r.json();(js.events||[]).forEach(function(ev){var state=ev.status&&ev.status.type&&ev.status.type.state;if(state==='pre')return;var comp=ev.competitions&&ev.competitions[0],cs=comp&&comp.competitors;if(!cs||cs.length<2)return;var c1=cs[0],c2=cs[1],t1=c1.team&&(c1.team.displayName||c1.team.shortDisplayName||c1.team.name||c1.team.location),t2=c2.team&&(c2.team.displayName||c2.team.shortDisplayName||c2.team.name||c2.team.location),s1=c1.score,s2=c2.score;if(!t1||!t2||s1===undefined||s2===undefined)return;var de=String(ev.date||'').slice(0,10)||(dia.slice(0,4)+'-'+dia.slice(4,6)+'-'+dia.slice(6,8)),p1=s1+' x '+s2,p2=s2+' x '+s1,k1=chave(de,t1,t2),k2=chave(de,t2,t1);if(S[k1]!==p1){S[k1]=p1;mudou=true}if(S[k2]!==p2){S[k2]=p2;mudou=true}})}catch(e){console.warn('Falha ESPN placar:',e)}}));if(mudou){if(typeof $==='function'&&$('upd'))$('upd').textContent='ESPN '+new Date().toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'});render()}marcarBrasil()}catch(e){console.warn('Falha geral ESPN:',e)}rodando=false}
function iniciar(){marcarBrasil();setTimeout(function(){buscar(true)},2500);setInterval(function(){buscar(false);marcarBrasil()},30000);window.addEventListener('focus',function(){buscar(true);marcarBrasil()});document.addEventListener('visibilitychange',function(){if(!document.hidden){buscar(true);marcarBrasil()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',iniciar);else iniciar();
})();
